# Generated by Django 4.0.1 on 2022-01-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=15)),
                ('description', models.TextField(max_length=500)),
                ('publish_at', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(default=1200)),
                ('vacancy', models.IntegerField(default=1)),
                ('experince', models.IntegerField(default=0)),
            ],
        ),
    ]
