# Generated by Django 4.0.1 on 2022-01-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.categorie'),
            preserve_default=False,
        ),
    ]
