# Generated by Django 4.0.1 on 2022-01-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_slug_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='coverletter',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='cv',
            field=models.FileField(null=True, upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
