# Generated by Django 4.0.1 on 2022-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_apply_job_coverletter_alter_apply_job_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='coverletter',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='cv',
            field=models.FileField(default='', upload_to='cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='website',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
